table:
  name: country_delivery_configs
  schema: public
object_relationships:
  - name: delivery_config
    using:
      foreign_key_constraint_on: config_key
select_permissions:
  - role: agent
    permission:
      columns:
        - id
        - country_code
        - config_key
        - config_value
        - data_type
        - created_at
        - updated_at
      filter: {}
      allow_aggregations: true
  - role: anonymous
    permission:
      columns:
        - id
        - country_code
        - config_key
        - config_value
        - data_type
        - created_at
        - updated_at
      filter: {}
      allow_aggregations: true
  - role: business
    permission:
      columns:
        - id
        - country_code
        - config_key
        - config_value
        - data_type
        - created_at
        - updated_at
      filter: {}
      allow_aggregations: true
  - role: client
    permission:
      columns:
        - id
        - country_code
        - config_key
        - config_value
        - data_type
        - created_at
        - updated_at
      filter: {}
      allow_aggregations: true
  - role: user
    permission:
      columns:
        - id
        - country_code
        - config_key
        - config_value
        - data_type
        - created_at
        - updated_at
      filter: {}
      allow_aggregations: true
