table:
  name: delivery_configs
  schema: public
select_permissions:
  - role: agent
    permission:
      columns:
        - id
        - config_key
        - description
        - created_at
        - updated_at
      filter: {}
      allow_aggregations: true
  - role: anonymous
    permission:
      columns:
        - id
        - config_key
        - description
        - created_at
        - updated_at
      filter: {}
      allow_aggregations: true
  - role: business
    permission:
      columns:
        - id
        - config_key
        - description
        - created_at
        - updated_at
      filter: {}
      allow_aggregations: true
  - role: client
    permission:
      columns:
        - id
        - config_key
        - description
        - created_at
        - updated_at
      filter: {}
      allow_aggregations: true
  - role: user
    permission:
      columns:
        - id
        - config_key
        - description
        - created_at
        - updated_at
      filter: {}
      allow_aggregations: true
array_relationships:
  - name: country_delivery_configs
    using:
      manual_configuration:
        column_mapping:
          config_key: config_key
        insertion_order: null
        remote_table:
          name: country_delivery_configs
          schema: public
